services:
  server:
    build: ./server
    image: ajaymare/vortex-server:latest
    container_name: vortex-server
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "80:80"
      - "443:443"
      - "5201:5201"
      - "5201:5201/udp"
      - "5202:5202"
      - "5202:5202/udp"
      - "5203:5203"
      - "5203:5203/udp"
      - "5004-5007:5004-5007/udp"
      - "9999:9999"
      - "53:53/udp"
      - "21:21"
      - "21100-21110:21100-21110"
      - "2222:2222"
      - "8082:8082"
      - "8443:8443"
    restart: unless-stopped
